### ISSUE TITLE
Bug in record deletion

### ISSUE THREAD

**Issue by WolframHempel** [hoxton-one/deepstream.io#25]
```
TypeError: Cannot read property 'logger' of null
    at RecordDeletion._done (/ds-server/node_modules/deepstream.io/src/record/record-deletion.js:61:15)
    at RecordDeletion._checkIfDone (/ds-server/node_modules/deepstream.io/src/record/record-deletion.js:49:8)
    at try_callback (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:321:14)
    at ReplyParser.emit (events.js:107:17)
    at ReplyParser.send_reply (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/lib/parser/javascript.js:189:22)
    at RedisClient.on_data (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/ds-server/node_modules/deepstream.io-cache-redis/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by WolframHempel** [comment]
Fixed this issue in release 0.4.1 and added additional test suite
