### ISSUE TITLE
Error when try to install 

### ISSUE THREAD

**Issue by hopewise** [hoxton-one/deepstream.io#77]
Here is what I get when try to install deepstream.io:
Any help is appreciated ( I am on ubuntu 14.04 )
```
samir@samir-OptiPlex-7020:~$ npm install deepstream.io
npm WARN package.json node@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/deepstream.io
npm http 304 https://registry.npmjs.org/deepstream.io
npm http GET https://registry.npmjs.org/colors/1.0.3
npm http GET https://registry.npmjs.org/engine.io/1.6.4
npm http GET https://registry.npmjs.org/minimist/1.2.0
npm http 304 https://registry.npmjs.org/colors/1.0.3
npm http 304 https://registry.npmjs.org/engine.io/1.6.4
npm http 304 https://registry.npmjs.org/minimist/1.2.0
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/debug/2.2.0
npm http GET https://registry.npmjs.org/ws/0.8.1
npm http GET https://registry.npmjs.org/engine.io-parser/1.2.4
npm http GET https://registry.npmjs.org/accepts/1.1.4
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/ws/0.8.1
npm http 304 https://registry.npmjs.org/accepts/1.1.4
npm http 304 https://registry.npmjs.org/debug/2.2.0
npm http 304 https://registry.npmjs.org/engine.io-parser/1.2.4
npm http GET https://registry.npmjs.org/negotiator/0.4.9
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/after/0.8.1
npm http GET https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http GET https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/blob/0.0.4
npm http GET https://registry.npmjs.org/has-binary/0.1.6
npm http GET https://registry.npmjs.org/utf8/2.1.0
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/negotiator/0.4.9
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http 304 https://registry.npmjs.org/after/0.8.1
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http 304 https://registry.npmjs.org/blob/0.0.4
npm http 304 https://registry.npmjs.org/utf8/2.1.0
npm http 304 https://registry.npmjs.org/has-binary/0.1.6
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/bufferutil
npm http 304 https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/utf-8-validate
npm htt'p 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings

> utf-8-validate@1.2.1 install /home/samir/node_modules/deepstream.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild


> bufferutil@1.2.1 install /home/samir/node_modules/deepstream.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-76-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/samir/node_modules/deepstream.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-76-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/samir/node_modules/deepstream.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing bufferutil@1.2.1
deepstream.io@0.7.1 node_modules/deepstream.io
├── minimist@1.2.0
├── colors@1.0.3
└── engine.io@1.6.4 (base64id@0.1.0, debug@2.2.0, accepts@1.1.4, engine.io-parser@1.2.4, ws@0.8.1)
```

**Comment by hopewise** [comment]
Ok, I have installed it, sorry, I wish I can delete this issue, however, I will close it.

**Comment by WolframHempel** [comment]
Hi @hopewise,

no worries at all. What failed is an optional dependency that can be pre-compiled using [node-gyp](https://github.com/nodejs/node-gyp) (a generic cross platform compiler that is used by a lot of node projects). If you don't have it installed, no problem though. The worst that can happen is that a certain aspect of deepstream might run a little bit slower than it would with precompiled code.

**Comment by hopewise** [comment]
Thanks for quick reply, it would be great to have a docker image that has
all modules installed ..
